export const CLICK_UPDATE_VALUE = 'CLICK_UPDATE_VALUE';
export const COUNTER_UPDATE_INCREMENT = 'COUNTER_UPDATE_INCREMENT';
export const COUNTER_UPDATE_DECREMENT = 'COUNTER_UPDATE_DECREMENT';
export const HOME_UPDATE_VALUE = 'HOME_UPDATE_VALUE';